import type { Metadata } from "next";
import Header from "@/components/Header";
import localFont from "next/font/local";
import "./globals.css";

const satoshi = localFont({
  src: "../fonts/Satoshi-Regular.otf",
  weight: "400",
  style: "normal",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} antialiased h-screen bg-[#161722] p-[16px] pt-[14px]`}
      >
        <Header />
        <div className="inner size-full bg-white rounded-[12px]">
          {children}
        </div>
      </body>
    </html>
  );
}
